### ISSUE TITLE
APIParis

### ISSUE THREAD

**Issue by AlFalahTaieb** [parisnumerique/makeMeAPI#2]
Bonjour , j'aimerai faire une demande concernant la limitation de l'utilisation de l'API http://api.paris.fr ., je suis étudiant et dans le cadre d'un projet en programmation si c'est possible d'avoir plus que 1000 requêtes ?

Bonne journée à vous !

**Comment by proustibat** [comment]
@AlFalahTaieb pourquoi tu ne demandes pas ici ? http://www.paris.fr/contact
